server:
  port: 8099
  servlet:
    context-path: /
spring:
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/image?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

logging:
  level: 
    com.cy.mapper: debug
    
mybatis-plus:
  type-aliases-package: com.cy.pojo
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true